# Generated by Django 5.1.2 on 2024-10-22 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwisaver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='fees',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='returns',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='badges',
            field=models.ManyToManyField(to='kiwisaver.badge'),
        ),
        migrations.CreateModel(
            name='FundRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('-', 'Unknown')], default='-', max_length=1)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiwisaver.fund')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiwisaver.rating')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='ratings',
            field=models.ManyToManyField(through='kiwisaver.FundRating', to='kiwisaver.rating'),
        ),
    ]
