# Generated by Django 5.1.2 on 2024-10-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwisaver', '0002_badge_rating_fund_fees_fund_returns_fund_badges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrating',
            name='score',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
