# Generated by Django 5.1.2 on 2024-10-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwisaver', '0003_alter_fundrating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='badges',
            field=models.ManyToManyField(blank=True, to='kiwisaver.badge'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='companies',
            field=models.ManyToManyField(blank=True, through='kiwisaver.Holding', to='kiwisaver.company'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='returns',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundrating',
            name='score',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='short_desc',
            field=models.CharField(max_length=400, verbose_name='short description'),
        ),
    ]
