# Generated by Django 5.1.2 on 2024-10-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwisaver', '0005_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(null=True, upload_to='media/badges'),
        ),
    ]
